name: Run Azure Login with OpenID Connect and PowerShell
on: [push, workflow_dispatch]

permissions:
      id-token: write
      contents: read
      
jobs: 
  Windows-latest:
      runs-on: linux-latest
      env:
            ARM_CLIENT_ID: 048da38b-f8a9-4a71-ab7e-964c9aa37b97
            # ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
            ARM_SUBSCRIPTION_ID: 905bb708-6be9-4992-b89b-5ff983353520
            ARM_TENANT_ID: f3597b7d-1aa8-4fc0-8c77-26cc6f10333b
      environment: production
      steps:
        - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
          uses: azure/login@v1
          with:
            client-id: 048da38b-f8a9-4a71-ab7e-964c9aa37b97
            tenant-id: f3597b7d-1aa8-4fc0-8c77-26cc6f10333b
            subscription-id: 905bb708-6be9-4992-b89b-5ff983353520
            enable-AzPSSession: true

        - name: 'Terraform Format'
          uses: hashicorp/terraform-github-actions@master
          with:
            tf_actions_version: 0.14.8
            tf_actions_subcommand: 'fmt'
            tf_actions_working_dir: "."
         
        - name: 'Terraform Init'
          uses: hashicorp/terraform-github-actions@master
          with:
            tf_actions_version: 0.14.8
            tf_actions_subcommand: 'init'
            tf_actions_working_dir: "."
 
        - name: 'Terraform Validate'
          uses: hashicorp/terraform-github-actions@master
          with:
            tf_actions_version: 0.14.8
            tf_actions_subcommand: 'validate'
            tf_actions_working_dir: "."
         
        - name: 'Terraform Plan'
          uses: hashicorp/terraform-github-actions@master
          with:
            tf_actions_version: 0.14.8
            tf_actions_subcommand: 'plan'
            tf_actions_working_dir: "."
 
        - name: Terraform Apply
          if: github.ref == 'refs/heads/main'
          uses: hashicorp/terraform-github-actions@master
          with:
            tf_actions_version: 0.14.8
            tf_actions_subcommand: 'applya'
            tf_actions_working_dir: "."
